In [ ]:
#Q1Combining a one and a two-dimensional NumPy Array
import numpy as np

a = np.array([1,2,3])

b = np.array([[4,5,6],
              [7,8,9]])

result = np.vstack((a,b))
print(result)

a = np.array([1,2])
result = np.hstack((b,a.reshape(2,1)))
print(result)   

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6 1]
 [7 8 9 2]]


In [15]:
import numpy as np

a = np.array([[1,2,3]])
b = np.array([[4,5,6],
              [7,8,9]])
result = np.concatenate((a,b), axis = 0)
print(result)

x = np.array([[1],
              [2]])
result = np.concatenate((b,x), axis = 1)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6 1]
 [7 8 9 2]]


In [ ]:
#Q2Flatten a 2d numpy array into 1d array

import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])
flat = arr.flatten()
print(flat)

flat = arr.reshape(-1)
print(flat)

flat = arr.ravel()
print(flat)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
#Q3Reverse a numpy array
import numpy as np
arr = np.array([1,2,3,4,5])
rev = arr[::-1]
print(rev)

[5 4 3 2 1]


In [ ]:
# Q4 Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy
import numpy as np
arr = np.array([3,7,1,9,4])
maximum = np.max(arr)
print(maximum)
minimum = np.min(arr)
print(minimum)

arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2.shape)
rows = arr2.shape[0]
cols = arr2.shape[1]
print(rows)
print(cols)

# Select Elements from Array
# access every element
for row in arr2:
    for element in row:
        print(element)
# access specific element
print(arr2[1][2])

print("\nSum of 2d array using loop: ")
arr3 = np.array([[1,2],
                 [3,4]])

total = 0

for row in arr3:
    for element in row:
        total += element

print(total)

print("\nAdding,subtracting,multiply, divide array: ")
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a-b)
print(a*b)
print(a/b)


9
1
(2, 3)
2
3
1
2
3
4
5
6
6

Sum of 2d array using loop: 
10

Adding,subtracting,multiply, divide array: 
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Q5 Iterate 3D array using for loop and nditer 

import numpy as np

arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [7,8,9],
        [10,11,12]
    ]
])

print(arr.shape)

for layer in arr:
    for row in layer:
        for element in row:
            print(element)

for element in np.nditer(arr):
    print(element)            

(2, 2, 3)
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Q6 Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg)

import numpy as np

arr1 = np.array([3, 4])
arr2 = np.array([1, 0])


avg = (arr1 + arr2) / 2

print("Average of NumPy arrays:\n", avg)


# Calculate average mean median mode values of two NumPy 2d-arrays

import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[3, 4],
                 [5, 6]])

arr2 = np.array([[1, 0],
                 [2, 3]])

# Average of two arrays

avg = (arr1 + arr2) / 2

print("Average of NumPy arrays:\n", avg)


# Mean

mean1 = np.mean(arr1)
mean2 = np.mean(arr2)

print("\nMean of arr1:", mean1)
print("Mean of arr2:", mean2)

# Median

median1 = np.median(arr1)
median2 = np.median(arr2)

print("\nMedian of arr1:", median1)
print("Median of arr2:", median2)

# Mode using NumPy only

# Flatten arrays into 1D
flat1 = arr1.flatten()
flat2 = arr2.flatten()

# Find unique values and counts
values1, counts1 = np.unique(flat1, return_counts=True)
values2, counts2 = np.unique(flat2, return_counts=True)

# Find mode
mode1 = values1[np.argmax(counts1)]
mode2 = values2[np.argmax(counts2)]

print("\nMode of arr1:", mode1)
print("Mode of arr2:", mode2)


Average of NumPy arrays:
 [2. 2.]
Average of NumPy arrays:
 [[2.  2. ]
 [3.5 4.5]]

Mean of arr1: 4.5
Mean of arr2: 1.5

Median of arr1: 4.5
Median of arr2: 1.5

Mode of arr1: 3
Mode of arr2: 0
