In [ ]:
# 1) Create numpy array and perform following operation.

# Convert 1D array to 2D

import numpy as np
a = np.array([1,2,3,4,5,6])
print(a,a.shape)

a_2d = a.reshape(3,2)
print(a_2d)

[1 2 3 4 5 6] (6,)
[[1 2]
 [3 4]
 [5 6]]


In [13]:
# Print Array Attributes(Like shape, dimension, data type, itemsiz)
import numpy as np
b = np.array([1,2,3,4,5,6])
print("\nShape: ",b.shape)
print("\nDimension: ",b.ndim)
print("\nDataType: ",b.dtype)
print("\nItemSize: ",b.itemsize)



Shape:  (6,)

Dimension:  1

DataType:  int64

ItemSize:  8


In [16]:
# Create a 3x3 NumPy array of all 9
import numpy as np
a = np.full((3,3),9)
print(a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
# Create a 1d array of 10 evenly spaced values between 25 and 125
import numpy as np
a = np.linspace(25,125,10)
print(a)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [20]:
# Convert a Python list into a NumPy array
import numpy as np

lst = [[1,2,3,4],
       [4,5,6,7],
       [2,3,4,5]]
print(lst)

arr = np.array(lst)
print(arr)


[[1, 2, 3, 4], [4, 5, 6, 7], [2, 3, 4, 5]]
[[1 2 3 4]
 [4 5 6 7]
 [2 3 4 5]]


In [21]:
# Reverse a 1d NumPy array
import numpy as np
arr = ([1,2,3,4])
print(arr[::-1])

[4, 3, 2, 1]


In [36]:
# Create a 4x4x3 array and extract value at its second set, first row and last column.

import numpy as np

arr = np.arange(1,49)
y = (arr.reshape(4,4,3))
print(y)

val = y[1,0,2]
print(val)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
15


In [42]:
# Create a 4x4 and Extract Odd Rows and Even Columns

import numpy as np
arr = np.arange(1,17).reshape(4,4)
print(arr)

res = arr[1::2,0::2]
print(res)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  7]
 [13 15]]


In [46]:
# Slice the first two rows and first two columns of second set from a 4x4x3 array

import numpy as np

arr = np.arange(1,49)
y = (arr.reshape(4,4,3))
print(y)

res= y[1,0:2,0:2]
print(res)



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]
[[13 14]
 [16 17]]


In [48]:
# Replace all odd numbers in a NumPy array with -1 by iterating using for loop [[23, 56, 78, 93],[71, 82,13, 24]]
import numpy as np

arr = np.array([[23, 56, 78, 93],
                [71, 82, 13, 24]])


rows,columns = arr.shape
for i in range(rows):
    for j in range(cols):
        if arr[i, j] % 2 != 0:   # check odd number
            arr[i, j] = -1

print(arr)





[[-1 56 78 -1]
 [-1 82 -1 24]]


In [49]:
# Get the indices of non-zero elements in an array [1, 0, 2, 8, 3, 0, 4]
import numpy as np

arr = np.array([1, 0, 2, 8, 3, 0, 41])

indices = np.nonzero(arr)

print(indices)

(array([0, 2, 3, 4, 6]),)


In [51]:
# Perform arithmetic operations on two NumPy arrays element-wise

# Add two NumPy arrays element by element. Multiply two NumPy arrays element by element.

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

add = arr1+arr2
print(add)
mul = arr1*arr2
print(mul)

[ 6  8 10 12]
[ 5 12 21 32]


In [52]:
# Write a code to compute the dot product of two NumPy arrays arr1 [15, 20, 25] arr2 [10,40,37]

import numpy as np

arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

res = np.dot(arr1,arr2)
print("Dot Product = ",res)

Dot Product =  1875
